### ISSUE TITLE
Exposed sinon stubs are not compatible with latest sinon

### ISSUE THREAD

**Issue by HughePaul** [lennym/reqres#5]
Exposed sinon stubs are from sinon 1.x.x and are not entirely compatible with sinon-chai assertions from sinon 4.x.x

**Comment by HughePaul** [comment]
exposing sinon as a global seems to be a convention; perhaps the library could use a global sinon and fall back to its own version.

**Comment by lennym** [comment]
@HughePaul Thanks for opening an issue. I've published a new (major) version with an up-to-date version of sinon. I will try to do something clever like you suggest to allow a user to bring their own sinon, but since that'll need code writing, and it's 5pm on a Friday, it'll have to wait until next week.

**Comment by HughePaul** [comment]
Or change to be in peerDependencies, and then add to devDependencies so no specific veersion gets installed

**Comment by HughePaul** [comment]
:+1: ah cool, We were spending a Friday looking at updating dependencies, no rush :)

**Comment by lennym** [comment]
@HughePaul I wasn't happy with the idea of a peer dependency as it should be possible for someone to use `reqres` without caring about sinon at all, and forcing my implementation detail onto the user didn't feel friendly.

Anyway, I've pushed an update at `v2.1.0` which allows an implementation to set its own version of sinon (or indeed any other lib that exposes a similar API). See https://github.com/lennym/reqres#customisation for details.

**Comment by lennym** [comment]
Closing. Thanks for your contribution @HughePaul
